SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE answer RESTART IDENTITY;
TRUNCATE TABLE probation RESTART IDENTITY;
TRUNCATE TABLE report RESTART IDENTITY;
TRUNCATE TABLE users RESTART IDENTITY;
TRUNCATE TABLE shelter RESTART IDENTITY;
TRUNCATE TABLE session RESTART IDENTITY;
TRUNCATE TABLE volunteer_contact RESTART IDENTITY;
TRUNCATE TABLE shelter_user RESTART IDENTITY;